### ISSUE TITLE
Disqus Comments Alternative

### ISSUE THREAD

**Issue by grand-lotus-iroh** [godofredoninja/Mapache#107]
Disqus in my opinion is garbo - I like how it's easy but on a censorship and tracking privacy level, I think it's horrible.

I've had alot of success with https://commento.io/ -- perhaps integrate this into the theme, if disqus or facebook comments or w/e is being used instead.

**Comment by VincentTam** [comment]
Hi, this is the maintainer of @staticmanlab, a public GitLab instance of [Staicman](https://staticman.net/).  Here's some shortcomings of popular 3rd-party commenting systems.

1. Gitment, Gitalk and Utterance support only GitHub, and they require user login before commenting. This can scare away many non programmers from leaving a comment to your posts. Besides, comments are part of the site's static content, not a software package problem. As a result, using GtiHub issues for comment storage is wrong in principle and bad in terms of SEO.
2. Commento is not free as in free beer.  For a personal blog with small traffic, you might find a monthly fee of $5 too expensive.
3. Disqus and Isso contain a 3rd-party script to be loaded during page rendering. The code block for loading each of them shows that the static comments are not rendered as static HTML code. This hinders search engines from grabbing the comments, which are part of the site's content.  As a result, that leads to suboptimal SEO.

You may avoid these problems by switching to [Staticman](https://staticman.net), which makes use of GitHub/GitLab Pull/Merge Requests instead of issues. Under Staticman's model, static comments are YML/JSON files stored in the remote GitHub/GitLab repo (usually under data/comments, configurable through the path parameter in root-level staticman.yml), and through a static blog generator (Jekyll/Hugo/etc), the stored data are rendered as part of the content. This gives a total ownership of a static site's comments.

**Comment by godofredoninja** [comment]
Hi @grand-lotus-iroh @VincentTam 

:thinking: I don't think it's ideal to support many comments.

But, you can add your comments. You only have to edit the file `partilas/article/article-comments.hbs`

https://github.com/godofredoninja/Mapache/blob/bd89c4c4b096df7300593d5de33bc72d362f841b/partials/article/article-comments.hbs#L10

https://github.com/godofredoninja/Mapache/blob/bd89c4c4b096df7300593d5de33bc72d362f841b/partials/article/article-body.hbs#L25
