### ISSUE TITLE
"Header ID" Non-English Character replacement

### ISSUE THREAD

**Issue by ysarac** [godofredoninja/Mapache#141]
Hello,
I have an issue with Ghost system that it replacing non-english charecters with the alternative characters on URL but on header (h1-h6) ID's replacing them with dash "-". 

Example:
If title of article:  Çok Güzel Bir Yazı
Url is: /cok-guzel-bir-yazi
_(replaced ç with c, ü with u, ı with i)_

there is no problem so far, but when I use a header that contains a non-english character in the article, it does not replace non-english characters with alternatives in the ID, instead it uses "-".

Example: Header is "Çok Güzel Bir Yazı"
Html producing: `<h2 id="-ok-g-zel-bir-yaz-">Çok Güzel Bir Yazı</h2>`

I asked this on the official ghost forum, they directed me to a more authoritative person, and she did not respond.

Any solution for this issue?

**Comment by clementduveau** [comment]
Hello, 

First, this is related to Ghost, not to the theme itself. No fix will be provided.
Second, how is it a problem that your id doesn't have the right name ?

Regards

**Comment by godofredoninja** [comment]
Hello my friend.

 Thanks for using my Mapache theme.

 For me it would be an honor to help you, but unfortunately I will not be
able to do it, because my only computer is damaged and has been unusable.
This has caused my projects and updates for Ghost to stop.

 I am trying to get a new computer, to continue with the projects for
Ghost.  I don't know how long it will take to get one.


 I hope you understand me.

 Best regards.
