### ISSUE TITLE
loading more nothing happends

### ISSUE THREAD

**Issue by glodinas** [godofredoninja/Mapache#29]
Hi , I have installed your template on my ghost CMS. When I press loading more, Now new conntent is begin displayed. Do you know by any chance why? Because there is more content to show. What can I do to fix it?

website is https://cihatkaya.me/
you can check it live or look up the screenshot. 
![knipsel2](https://cloud.githubusercontent.com/assets/8988468/19246203/73e9b5d2-8f25-11e6-9e43-76c90a111a23.PNG)

**Comment by godofredoninja** [comment]
## The problem is caused by the redirection of http 

![](http://i.imgur.com/SrzarDp.png)

**Comment by glodinas** [comment]
I have stopt the https redirection and if I go to http://Cihat Kaya.me it works but if I surf to HTTPS://cihatkaya.me .
In other words this doesn't seem to be an issue with redirection but rather with SSL connection.

**Comment by glodinas** [comment]
Any suggestions on what can I do to get it to work over SSL ?  Thanks in advance. :)

**Comment by cmilanf** [comment]
Basically, you can't fetch content from an HTTP source when browsing a webpage through HTTPS (quite logical). It looks like there is a variable named urlPage that is the one that should point fetch() over the correct website. In my case, for some reason that variable contains http rather than https. I'm trying to trace back his origin in order to fix it, since hard-coding would be just a dirty fix.

**Comment by cmilanf** [comment]
I successfully traced back the issue. **urlPage** variable gets the URL from the Ghost official canonical link rel, that is **<link rel="canonical" href="http://yourblog.com">**. However, that HTML is not anywhere in the theme as it is generated dynamically by Ghost in **/core/server/config/url.js** and basically it says that it will only point to HTTPS in the case your *config.url* is HTTPS. Otherwise it will remain HTTP. Change that setting in your **config.js** and will work perfectly.

**Comment by godofredoninja** [comment]
To perform infinite pagination I'm using  link canonical `<link rel="canonical" href="http://yourblog.com\>`

To get an https url you simply have to configure it in ghost `config.js` and `production` as @cmilanf  says

for example

````js
production: {
        url: 'https://godofredo.ninja/blog',
        mail: {},
        database: {
            client: 'sqlite3',
            connection: {
                filename: path.join(__dirname, '/content/data/ghost.db')
            },
            debug: false
        },

        server: {
            host: '127.0.0.1',
            port: '2368'
        }
    },
```
