### ISSUE TITLE
sub menu

### ISSUE THREAD

**Issue by theraw** [godofredoninja/Mapache#96]
Hello,

i've been using this theme months ago so i got back and trying to use it again, trying to set my site up i got a question, anyway how to have a submenu at the header?!

Example this site is about movies/serials, so i have those tags, Action, Fantasy, Horror, etc, those can be solo placed however what i was thinking and wanted to do is for "Serials" to have it like
Serials : (sub menu below)
- Lucifer
- DBS
- DBH
- The Originals
- Etc

With easy words `https://www.w3schools.com/howto/howto_css_dropdown.asp`

is this possible to do?

**Comment by theraw** [comment]
btw i don't think this has anything to do with your theme, there is no error or a problem, if you can't or don't want to reply back will not be a problem if you close it..

**Comment by godofredoninja** [comment]
Hi @theraw 

How are you?

If possible. but the menu you have to add manually

I took a few minutes to create a menu. 

I have created a new branch [menu-dropdown](https://github.com/godofredoninja/Mapache/tree/menu-dropdown)

**To add the menu you have to go to the following file and edit with your respective links**

https://github.com/godofredoninja/Mapache/blob/7872847c3eedea43dfa5578649da583c5d6b6273/partials/menu/menu-dropdown.hbs#L2-L18

**Comment by theraw** [comment]
@godofredoninja Thank you very much for your time!

**Comment by theraw** [comment]
@godofredoninja sorry to disturb you again but i was spaming ghost support but this actually is a question which i should've done to you not to them so the problem is with video post template, example a video post with a embed from youtube looks normally and perfectly as it should be
https://allstartv.co/dragon-ball-super-1/

the video is placed in perfect place

but what if i want to embed a video.mp4 from a custom cdn example 
`https://cdn.allstartv.co/`
`https://cdn.allstartv.co/in.html`
`https://cdn.allstartv.co/dbh/2.mp4`
it will be displayed totally wrong :/  https://allstartv.co/dragon-ball-super-2/

is there anyway to display my custom cdn site videos as they show from youtube embed like a real video post ?!

i've tried for hours trying to fix this problem can't deal with it anymore i also did setup a custom oembed for my cdn https://cdn.allstartv.co/oembed and it still won't work it says there's some problem and somehow ghost is not including https when i submit url https://allstartv.co/db3-test/ (dev console)
https://cdn.allstartv.co/oembed?url=https%3A%2F%2Fcdn.allstartv.co%2Fdbh%2F2.mp4

still doesn't work idk what to do anymore, do you have any idea how to fix this?!

**Comment by godofredoninja** [comment]
Hi @theraw 

In the documentation I'm mentioning that videos support for video post format

[documentation](https://github.com/godofredoninja/Mapache#post-format)

— The following videos are supported
- vimeo
- Dailymotion
- Youtube
- Vid
- kickstarter

---

🤔 I think ghost does not support to embed mp4 videos

But if you want to be doing experiments with inserting videos. you can do the following. 

— But this will be manual as indicated by the following documentation 
- [https://developer.mozilla.org/](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Video_and_audio_content)
- https://www.w3schools.com/html/html5_video.asp

— Now all you have to do is open an Html block in your ghost editor.

For example:

```html
<div class="video-responsive">
   <video width="320" height="240" controls>
      <source src="https://cdn.allstartv.co/dbh/2.mp4" type="video/mp4">
   </video>
</div>
```

In the same ghost editor of your article on the right side is the section `code injection -> Post Footer` And paste the following code

```html
<script>
  $(window).on('load', function() {
    var iframeVideo = [
      'video',
    ];
        
    var $videoEmbed = $('.cc-video-embed');

    if ($videoEmbed.find('.video-responsive').length) { return }

    var firstVideo = $('.post-body-wrap').find(iframeVideo.join(','))[0];

    if (typeof firstVideo === 'undefined') { return }

    var $video = $(firstVideo);
    var $firstParentVideo = $video.parent('.video-responsive');
    var $secondParentVideo = $firstParentVideo.parent('.kg-embed-card');

    // Append Video
    if ($secondParentVideo.hasClass('kg-embed-card')) {
      $secondParentVideo.appendTo($videoEmbed);
    } else {
      $firstParentVideo.appendTo($videoEmbed);
    }
  })
</script>
```

This looks very ugly. But in experiment or practice mode you may be performing.

For a next version I will try to give support to the video tag so that they are responsive. but not for video post format

**Comment by theraw** [comment]
@godofredoninja actually that looks better then having it below author `https://allstartv.co/db-test-4/`
