### ISSUE TITLE
Feature request: Language picker

### ISSUE THREAD

**Issue by MaluNoPeleke** [godofredoninja/Mapache#98]
Since Ghost 2.0 it is possible to have multiple languages in Ghost.
It would be nice to have a language picker (with an automatic selection based on OS language) for all available languages on a site/page/post, similar to this request: https://forum.ghost.org/t/how-to-create-multilanguage-posts/2537

**Comment by godofredoninja** [comment]
Hello @MaluNoPeleke 

I'll add it for the next versions

**Comment by MaluNoPeleke** [comment]
Thanks in advance. Maybe it can be achieved with [hreflang](https://forum.ghost.org/t/how-to-create-multilanguage-posts/2537/6)?

**Comment by dimasirfandanu** [comment]
Hello I added language picker to Mapache, but I'm not sure how to alter defaul.hbs layout in page.hbs and post.hbs
`{{!-- Layout --}}
{{!< default }}

{{!-- lang switcher ---}}
{{#post}}
  {{#has tag="#id"}}
    {{#contentFor "lang"}}ID{{/contentFor}}
  {{else}}
    {{#contentFor "lang"}}EN{{/contentFor}}
  {{/has}}
{{/post}}`

I added hreflang to the theme but I don't know to alter {{!< default }} since I'm new to ghost.

**Comment by dimasirfandanu** [comment]
Hello I added language picker to Mapache, but I'm not sure how to alter defaul.hbs layout in page.hbs and post.hbs
This is my page.hbs:
```
{{!-- Layout --}}
{{!< default }}

{{!-- lang switcher ---}}
{{#post}}
  {{#has tag="#id"}}
    {{#contentFor "lang"}}ID{{/contentFor}}
  {{else}}
    {{#contentFor "lang"}}EN{{/contentFor}}
  {{/has}}
{{/post}}
```

I added hreflang to the theme but I don't know to alter {{!< default }} since I'm new to ghost.
